### ISSUE TITLE
Startup-warn: "UNKNOWN is neither a valid Integer"

### ISSUE THREAD

**Issue by RedstoneFuture** [Phoenix616/VersionConnector#10]
#### Used Version
version 1.6 (build 44)
  
#### Config
 ```yaml
join:
  main:
    versions:
      '335': lb
      '393': hs
      '477': lb
      UNKNOWN: lb
 ```
 

 
#### Full Log
```
[18:04:27] [main/WARN] [VersionConnector]: UNKNOWN is neither a valid Integer nor a string representation of a major protocol version?
[18:04:27] [main/INFO]: Enabled plugin VersionConnector version 1.6 (build 44) by Phoenix616
```

#### What is happening?
Is these WARN message necessary on the startup? I understand the check, but the "UNKNOWN" message is a valid default-value for this plugin setup.

#### Additional context
The plugin works fine with this config.
