### ISSUE TITLE
Forge detection in 1.15.2

### ISSUE THREAD

**Issue by HerrBeef** [Phoenix616/VersionConnector#6]
Hi,
i've a problem that it says i'm not using forge an so it connects me to the wrong server.
![grafik](https://user-images.githubusercontent.com/12501633/81173983-42b6bc00-8fa1-11ea-9e1f-9e532bbd5ab5.png)

my config:
```yaml
debug: true
start-balancing: -1
servers:
  vanilla:
    versions:
      '1.15': vanilla
    forge:
      '1.12': projectreboot
      '1.14': develop14
      '1.15': develop15
```
my config.yml of bungee:
```yaml
prevent_proxy_connections: false
listeners:
- query_port: 25565
  motd: '&1Flootly Network'
  tab_list: GLOBAL_PING
  query_enabled: false
  proxy_protocol: false
  ping_passthrough: false
  priorities:
  - develop15
  bind_local_address: true
  host: 0.0.0.0:25565
  max_players: 200
  tab_size: 60
  force_default_server: false
  forced_hosts:
    vanilla.floot.host: vanilla
    projectreboot.floot.host: projectreboot
    develop14.floot.host: develop14
    develop15.floot.host: develop15
remote_ping_cache: -1
network_compression_threshold: 256
permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
  - versionconnector.command
  - versionconnector.command.reload
  - versionconnector.command.config
  - versionconnector.command.check
  - versionconnector.command.check.other
  - versionconnector.command.check.all
log_pings: false
connection_throttle_limit: 3
server_connect_timeout: 5000
timeout: 30000
player_limit: -1
ip_forward: false
groups:
  HerrBeef:
  - admin
remote_ping_timeout: 5000
connection_throttle: 4000
log_commands: false
stats: c581ec42-02d9-4495-83c1-32f5b8c92834
online_mode: true
forge_support: true
disabled_commands:
- disabledcommandhere
servers:
  vanilla:
    motd: '&1Vanilla 1.15.2'
    address: floot.host:25570
    restricted: false
  projectreboot:
    motd: '&1Project Reboot 1.12.2'
    address: floot.host:25569
    restricted: false
  develop14:
    motd: '&1Develop14 1.14.4'
    address: floot.host:25567
    restricted: false
  develop15:
    motd: '&1Develop15 1.15.2'
    address: floot.host:25568
    restricted: false
```
